# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_auto_20161202_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createevent',
            old_name='Event_description',
            new_name='Event_detail',
        ),
        migrations.RenameField(
            model_name='createevent',
            old_name='title',
            new_name='Event_title',
        ),
    ]
