# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_auto_20161202_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_type',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
